### ISSUE TITLE
public_html showing blank

### ISSUE THREAD

**Issue by pprevalon** [braintree/braintree_php_example#15]
for some odd reason public_html/index keep showing blank how can i resolve this

**Comment by danakatz** [comment]
Hi @pprevalon, could you provide more information about what specific steps you used to set up and run the example? I can't seem to to reproduce this.

Make sure to complete all the [setup instructions](https://github.com/braintree/braintree_php_example#setup-instructions) if you haven't already!

**Comment by pprevalon** [comment]
I download "braintree_php_example" from your git then i place it in on my server. I rename the folder "braintree". To test this i then go to www.mysite.com/braintree/public_html/index.php this give me a blank white page. Its suppose to show me the sample page but I get nothing. If i type text in the file i get to see the text when in my browse but it does not show all of the other contents.

**Comment by danakatz** [comment]
Thanks for elaborating! The issue is likely caused by improper setup - in order for the example to work, you'll need to follow the [instructions in the README](https://github.com/braintree/braintree_php_example#setup-instructions) and then visit `http://localhost:3000/` in a browser on the same machine.
