### ISSUE TITLE
Braintree returns "processor_declined"

### ISSUE THREAD

**Issue by antgarmun** [braintree/braintree_php_example#20]
I am testing the implementation with a browser and I have this message every time. The Braintree api response returns "processor_declined" and doesn't show information about the token:
![imagen](https://cloud.githubusercontent.com/assets/17279637/24080308/700023b2-0c9c-11e7-93cf-1fd342590840.png)

**Comment by matthewarkin** [comment]
HI @antgarmun,
I believe you are trying to use a test card number (4111-1111-1111-1111) while using a set of production api keys. The test credit card numbers only work with a sandbox account (having them work in production would be bad since any person could buy stuff for free). You can sign up for a sandbox account at https://www.braintreepayments.com/sandbox

**Comment by antgarmun** [comment]
Hi @matthewarkin,
Thanks you so much, this was the problem!, all is fine. Do you know if this example works with Paypal?. 

Thanks you again.

**Comment by matthewarkin** [comment]
When PayPal is enabled in your Braintree account it should automatically be added to your Drop-in form. If you're having some issues getting PayPal to work, I'd suggest reaching out to the Braintree Support team at https://www.braintreepayments.com/contact

**Comment by antgarmun** [comment]
Ok, thanks you so much!!!
