### ISSUE TITLE
Payment method nonce represents an un-vaulted payment instrument

### ISSUE THREAD

**Issue by ShRyDeR** [braintree/braintree_php_example#48]
### General information

* Environment: Sandbox
* Language, language version, and OS: PHP 7.2 on Debian 10

### Issue description
Hello, I'm trying to create a Braintree_Subscription using the nonce I'm getting from the client-side dropin, this is my code:
```
	public function process(Request $request) {
		$payload = $request->payload;
		$nonce = $payload['nonce'];

		$status = Braintree_Subscription::create([
			'paymentMethodNonce' => $nonce,
			'planId' => 'solo',
		]);

		return response()->json([
			'data' => $status,
		]);
	}
```

But Briantree responds with `message: "Payment method nonce represents an un-vaulted payment instrument."`
The Drop-in config is nothing special, just `authorization` and `container` keys are set. 

What am I doing wrong here?

**Comment by crookedneighbor** [comment]
You must create a customer first (if you haven't already): https://developers.braintreepayments.com/reference/request/customer/create/php

Then add the payment method to the customer: https://developers.braintreepayments.com/reference/request/payment-method/create/php

Then use the token the resulting payment method (rather than the nonce, which was consumed to vault the payment method): https://developers.braintreepayments.com/reference/request/subscription/create/php

If you are creating Drop-in with a client token with a customer id, then any vaulted payment methods that are already on the customer will be displayed: https://developers.braintreepayments.com/guides/drop-in/customization/javascript/v3

(it will also auto-vault credit cards upon tokenization, so you can skip the server side vaulting step and just use the payment method nonce to create the subscription)

Further help with your integration is best found with our support team: https://help.braintreepayments.com/

Reach out to them if you have more questions.
