### ISSUE TITLE
3D secure missing

### ISSUE THREAD

**Issue by perlsol** [braintree/braintree_php_example#60]
This php example works great, however it is missing the now required 3D secure support, it would be useful if you added this to the example.
Can you add this request please?

**Comment by hollabaq86** [comment]
Hey @perlsol Thanks for reaching out! The demo apps are meant to be bare bones starting points for folks to fork and modify however they want to test things out with Braintree. Though 3D secure is required in some parts of the world, it's not required in all, which is why it's not a part of the demo and won't get added.

**Comment by perlsol** [comment]
This is confusing, your own overview, getting started and example integrations with drop-in documentation says... "These examples use our Drop-in UI for web for the client-side integration." and then link to this repo, yet the code in this repo is entirely different as to what is required, the snippets of code here and there do not help when trying to visualize the required flow when learning especially when they do not tally up with this example
